#EXTM3U
#EXTINF:-1,TV LEO
https://bf62f531f030.ngrok-free.app


#EXTINF:-1,TV IP LOCAL LR
http://192.168.18.104:8080

#EXTINF:-1,LRTV AOVIVO
https://live20.bozztv.com/akamaissh101/ssh101/lbr123/playlist.m3u8

#EXTINF:-1,TV ARAPUAN (Band PB)
https://5b7f3c45ab7c2.streamlock.net/arapuan/ngrp:arapuan_all/chunklist_w1532020336_b2128000.m3u8
#EXTINF:-1,RBATV (Band PA)
https://cdn.live.br1.jmvstream.com/w/LVW-15748/LVW15748_Yed7yzLuRC/chunklist.m3u8
#EXTINF:-1,Band
https://live2.eu-north-1b.cf.dmcdn.net/sec2(pW_Z6_cP5OLWpjkfu-oWD6IVIieeJuVkJvm2UAzluLzJbnHpt4K-_PS_FWfZLVq_iJCNP1JQh6sZ0Tl6VI2kt7b4cFkA75DAq5sd46FjIOn1fgNm7RJ86Tgu6MavDVLn)/cloud/3/x83vbd6/s/live-1080.m3u8#cell=lcf2-eu-north-1b
#EXTINF:-1,TV AMPLITUDE JUARA (Record MT)
https://cdn.live.br1.jmvstream.com/w/LVW-10842/LVW10842_513N26MDBL/chunklist.m3u8
#EXTINF:-1,TV TROPICAL (Record RN)
https://video08.logicahost.com.br/portaldatropical02/portaldatropical02/chunklist_w301123317.m3u8
#EXTINF:-1,ISTV
https://video08.logicahost.com.br/istvnacional/srt.stream/chunklist_w284856851.m3u8
#EXTINF:-1,RETRÔ CARTOON
https://stmv6.voxtvhd.com.br/retrotv/retrotv/playlist.m3u8?hls_ctx=p515e787
#EXTINF:-1,BSTV
https://video05.logicahost.com.br/gbsstudio/gbsstudio/chunklist_w2085739946.m3u8
#EXTINF:-1,CLOUDING TV
https://stmv8.samcast.com.br/redeclonetv/redeclonetv/chunklist_w1974422266.m3u8
#EXTINF:-1,LUCAS TV
https://stmv1.srvif.com/lucastv/lucastv/playlist.m3u8
#EXTINF:-1,GLN TV
https://stmv8.samcast.com.br/glnfilmes/glnfilmes/chunklist_w810192394.m3u8
#EXTINF:-1,TELA BRASIL TV
https://stmv.webtvninjas.com.br/mailson6054/mailson6054/chunklist_w656241485.m3u8
#EXTINF:-1,TV ARACATI
https://video04.logicahost.com.br/tvaracati/tvaracati/chunklist_w1860850665.m3u8
#EXTINF:-1,RETRÔ CARTOON 2
https://stmv6.voxtvhd.com.br/retrotv2/retrotv2/playlist.m3u8?hls_ctx=516546v2
#EXTINF:-1,RETRÔ CARTOON 3
https://stmv6.voxtvhd.com.br/retrotv3/retrotv3/playlist.m3u8?hls_ctx=7el5c44h
#EXTINF:-1,PORTO ALEGRE 24 HORAS TV
https://rtisoluctions.com.br/hls/test_src.m3u8
#EXTINF:-1,N SPORTS
https://video01.soultv.com.br/nsports/nsports/chunklist_w1596354218.m3u8
#EXTINF:-1,RUNTIME
https://stream.ads.ottera.tv/cl/250827d2n8l66kdhm59loqln60/1280x720_3071200_0_f.m3u8?i=728_2153
#EXTINF:-1,GOSPEL CARTOON
https://stmv1.srvif.com/gospelcartoon/gospelcartoon/playlist.m3u8
#EXTINF:-1,RUNTIME CINE ESPANTO
https://stream.ads.ottera.tv/cl/250827d2n8lq26k78n8qdr81i0/1280x720_3071200_0_f.m3u8?i=728_4865
#EXTINF:-1,RUNTIME CRIME
https://stream.ads.ottera.tv/cl/250827d2n8m0u2s9e3ek9pn8p0/1280x720_3071200_0_f.m3u8?i=728_4864
#EXTINF:-1,RECORD
https://cloud7-l2-user9874524101-2.s27-usa-cloudfront-net.online/secret_key/9a7e61533adaf924df9a8aca30bdfd16.m3u8
#EXTINF:-1,MEGAPIX
https://cloud7-l2-user9874524101-2.s27-usa-cloudfront-net.online/secret_key/58ba760358ddd8db445f4d3f4c842bf8.m3u8
#EXTINF:-1,PFC
https://cloud7-l2-user9874524101-2.s27-usa-cloudfront-net.online/secret_key/da0bd26f880d9ce1080944c2bda5d574.m3u8
#EXTINF:-1,TV CRISTAL (TV A Crítica TO)
https://tv03.zas.media:1936/tvcristalto/tvcristalto/chunklist_w1719541026.m3u8
#EXTINF:-1,QUIXERAMOBIM TV
https://srv4.zcast.com.br/flavio2481/flavio2481/playlist.m3u8?hls_ctx=4f78x796
#EXTINF:-1,TV RIO MADEIRA
https://stmv1.srvif.com/tvriomadeira/tvriomadeira/playlist.m3u8
#EXTINF:-1,FIFA+
https://c2657533.wurl.com/manifest/f36d25e7e52f1ba8d7e56eb859c636563214f541/UGxleC1icl9GSUZBUGx1c1BvcnR1Z3Vlc2VfSExT/41ec4765-3367-4021-b517-8a024bec2066/5.m3u8
#EXTINF:-1,TV Na Ativa Ao Vivo
https://cdn.live.br1.jmvstream.com/webtv/AVJ-13072/playlist/chunklist.m3u8
#EXTINF:-1,Lavras Ce Tv Web Ao Vivo
https://stmv1.srvif.com/lavrastv/lavrastv/playlist.m3u8
#EXTINF:-1,Tv Plug Ao Vivo
https://stmv3.voxtvhd.com.br/tvplug/tvplug/playlist.m3u8?hls_ctx=k9l91222

#EXTINF:-1 tvg-id="" tvg-name="TV Aberta" tvg-logo="" group-title="Canais | Abertos",SBT Brasília Ao Vivo
https://cdn.jmvstream.com/w/LVW-10801/LVW10801_Xvg4R0u57n/chunklist.m3u8

#EXTINF:-1 tvg-id="" tvg-name="TV Aberta" tvg-logo="" group-title="Canais | Abertos",TV Vila Real (Record MT) HD
https://cdn.jmvstream.com/w/LVW-10842/LVW10842_513N26MDBL/chunklist.m3u8

#EXTINF:-1 tvg-id="" tvg-name="TV Aberta" tvg-logo="" group-title="Canais | Abertos",Lavras Ce Tv
https://stmv1.srvstm.com/igor8605/igor8605/playlist.m3u8

#EXTINF:-1 tvg-id="" tvg-name="TV Aberta" tvg-logo="" group-title="Canais | Abertos",TV Centro Sul
https://5a0c3936c25c8.streamlock.net/tvcentrosultvstation/tvcentrosultvstation/playlist.m3u8

#EXTINF:-1 tvg-id="" tvg-name="TV Aberta" tvg-logo="" group-title="Canais | Abertos",Tv Tremembé
https://video05.logicahost.com.br/tvtremembe/tvtremembe/chunklist_w1934747615.m3u8

#EXTINF:-1 tvg-id="" tvg-name="TV Aberta" tvg-logo="" group-title="Canais | Abertos",TV Aurora
https://stream.skyspace.com.br:3466/stream/play.m3u8

#EXTINF:-1 tvg-id="" tvg-name="TV Aberta" tvg-logo="" group-title="Canais | Abertos",Cariri TV
https://video05.logicahost.com.br/cariritv/cariritv/chunklist_w10738583.m3u8

#EXTINF:-1,band
https://hqf6tcxuhk.singularcdn.net.br/live/019498af-1fdf-7df5-86bd-e4a6f588d6a7/s1/playlist-1080p.m3u8?sjwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmlfc3ViIjoiLzAxOTQ5OGFmLTFmZGYtN2RmNS04NmJkLWU0YTZmNTg4ZDZhNy8iLCJ1aWQiOiI4YTVhZjA2YS1mN2Q4LTQ4YzgtOTYyOS1lZjgwNjE5Mzg5M2IiLCJyYXUiOm51bGwsImJleSI6ZmFsc2UsImlpcCI6ZmFsc2UsIm5iZiI6MTc0NjgzNTY5NiwiaWF0IjoxNzQ2ODM1Njk2LCJleHAiOjE3NDY5MjIwOTYsImp0aSI6IjhhNWFmMDZhLWY3ZDgtNDhjOC05NjI5LWVmODA2MTkzODkzYiIsImlzcyI6IlNwYWxsYSJ9.TJvchUL_u9sRvGIxY0Y-caJ3MeJ5kNB1VImHXNw_5gQ&uid=8a5af06a-f7d8-48c8-9629-ef806193893b&magica=sim

#EXTINF:-1,TV ACARATI
https://video04.logicahost.com.br/tvaracati/tvaracati/playlist.m3u8

#EXTINF:-1,TV Metropole
https://cdn-fundacao-2110.ciclano.io:1443/fundacao-2110/fundacao-2110/chunklist_w1287194090.m3u8

#EXTINF:-1,TVC - TV Ceará
https://cdn.jmvstream.com/w/AVJ-12940/playlist/chunklist.m3u8

#EXTINF:-1,Tv Ximenes
https://stmv2.samcast.com.br/radiotvximenesfm/radiotvximenesfm/playlist.m3u8

#EXTINF:-1,Tv Padre Cicero
https://video01.logicahost.com.br/tvpadrecicero/tvpadrecicero/playlist.m3u8

#EXTINF:-1,Tv Nordeste
https://cdn.jmvstream.com/w/AVJ-13064/playlist/playlist.m3u8

#EXTINF:-1,Tv Tremembé
https://video05.logicahost.com.br/tvtremembe/tvtremembe/playlist.m3u8

#EXTINF:-1,TV União (Rede União) Ao Vivo
https://stmv1.samcast.com.br/josealberto9608/josealberto9608/playlist.m3u8

#EXTINF:-1,TV Capital Ao Vivo
https://stmv7.samcast.com.br/raimundoanselmolimamororo9090/raimundoanselmolimamororo9090/playlist.m3u8

#EXTINF:-1,Canal FDR Ao Vivo
https://stmv1.transmissaodigital.com/ronald6259/ronald6259/playlist.m3u8

#EXTINF:-1,CHD TV Ao Vivo
https://stmv1.liveplushd.com.br/chdtv/chdtv/playlist.m3u8

#EXTINF:-1,Tv Sul Cariri Ao Vivo
https://5a2b083e9f360.streamlock.net/tsctv/tsctv.sdp/playlist.m3u8

#EXTINF:-1,Sertão TV Ao Vivo
http://wz4.dnip.com.br/sertaotv/sertaotv.sdp/playlist.m3u8

#EXTINF:-1,Tv Meu Xodó Ao Vivo
https://5d82644094cc0.streamlock.net/8192/8192/playlist.m3u8

#EXTINF:-1,Tv Ibiapabana IBITV Ao Vivo
https://stmv1.duvoxtv.com.br/gamer/gamer/playlist.m3u8

#EXTINF:-1,Camocim TV
https://5c483b9d1019c.streamlock.net/8172/8172/chunklist_w341983832.m3u8

#EXTINF:-1,Tv Liberdade Pacajus Ao Vivo
https://srv1.paineldevideo.com/liberdaderadioetv/liberdaderadioetv/playlist.m3u8

#EXTINF:-1,Tv Iracema Ao Vivo
https://stmv1.srvstm.com/iracematv/iracematv/playlist.m3u8

#EXTINF:-1,Tv Assembléia Ceará
https://jjn5dkk9bd.zoeweb.tv/z404-live/stream/playlist.m3u8

#EXTINF:-1,TV Serra Verde Ao Vivo
https://cdn.jmvstream.com/w/AVJ-13064/playlist/playlist.m3u8

#EXTINF:-1,Tv Centro Sul Ao Vivo
https://5a0c3936c25c8.streamlock.net/tvcentrosultvstation/tvcentrosultvstation/playlist.m3u8

#EXTINF:-1,TV Precabura Ao Vivo
https://srv1.zcast.com.br/webtvprecabura/webtvprecabura/playlist.m3u8

#EXTINF:-1,Lavras Ce Tv Web Ao Vivo
https://stmv1.srvstm.com/igor8605/igor8605/playlist.m3u8

#EXTINF:-1,TV Boqueirão Ao Vivo
https://srv3.zcast.com.br/tvboqueirao/tvboqueirao/playlist.m3u8

#EXTINF:-1,TV Na Ativa Ao Vivo
https://cdn.jmvstream.com/w/AVJ-13072/playlist/playlist.m3u8

#EXTINF:-1,Filadélfia Web Tv Ao Vivo
https://stmv2.samcast.com.br/marcostimotheo5865/marcostimotheo5865/playlist.m3u8

#EXTINF:-1,Web Tv Piquet Ao Vivo
https://stmv2.samcast.com.br/francisconicomedes5798/francisconicomedes5798/chunklist_w669765239.m3u8

#EXTINF:-1,Tv Potiguara Ao Vivo
https://stmv1.samcast.com.br/francisco1875/francisco1875/playlist.m3u8

#EXTINF:-1,Web Tv Cine Ao Vivo
https://stmv1.srvif.com/tvserie/tvserie/playlist.m3u8

#EXTINF:-1,Tv Nova Play Ao Vivo
https://srv4.zcast.com.br/tvnovaplay/tvnovaplay/playlist.m3u8

#EXTINF:-1,Bons Tempos Ao Vivo
https://stmv1.srvif.com/canal29/canal29/playlist.m3u8

#EXTINF:-1,Tv Loading Ao Vivo
https://stmv1.srvif.com/loadingtv/loadingtv/playlist.m3u8

#EXTINF:-1,CinePIX TV Ao Vivo
https://stmv3.voxtvhd.com.br/leonardo/leonardo/playlist.m3u8

#EXTINF:-1,Rede Clouding TV Ao Vivo
https://stmv1.paineltv.net/redeclonetv/redeclonetv/playlist.m3u8

#EXTINF:-1,Tv Osório News Ao Vivo
https://serv2.videovox.pw/video13154/video13154/playlist.m3u8

#EXTINF:-1,Runtime Ação Ao Vivo
https://stream.ads.ottera.tv/playlist.m3u8?network_id=2552

#EXTINF:-1,GLN TV Ao Vivo
https://stmv1.paineltv.net/glnfilmes/glnfilmes/playlist.m3u8

#EXTINF:-1,Tv Confiego Ao Vivo
https://stmv1.voxtvhd.com.br/tvconfiegogospel/tvconfiegogospel/playlist.m3u8

#EXTINF:-1,TV CARIOCA
https://a.cdni.live/tvcarioca/tvcarioca/playlist.m3u8

#EXTINF:-1,Tv Jornal do Nordeste Ao Vivo
https://video01.logicahost.com.br/tvjornaldonordeste/tvjornaldonordeste/chunklist_w309686598.m3u8

#EXTINF:-1,ULBTV
https://stmv1.paineltv.net/ulbtv/ulbtv/playlist.m3u8

#EXTINF:-1,VIVA TV
https://srv4.zcast.com.br/telavivatv/telavivatv/playlist.m3u8

#EXTINF:-1,CHANNEL 1
https://stmv1.srvif.com/channel1/channel1/playlist.m3u8

#EXTINF:-1,TV CEI Ao Vivo
https://stmv7.samcast.com.br/eduardo6272/eduardo6272/playlist.m3u8

#EXTINF:-1,Tv J.SID Ao Vivo
https://video05.logicahost.com.br/tvjsid/tvjsid/playlist.m3u8

#EXTINF:-1,TV ALAGOA
https://stmv4.voxtvhd.com.br/tvlagoadantas/tvlagoadantas/playlist.m3u8

#EXTINF:-1,TV NBT Ao Vivo
https://isaocorp.cloudecast.com/nbt/index.fmp4.m3u8

#EXTINF:-1,CTV
https://stmv1.samcast.com.br/ctvpb/ctvpb/playlist.m3u8

#EXTINF:-1,VIVA WEBTV
https://video01.kshost.com.br/cypriano46326/cypriano46326/playlist.m3u8

#EXTINF:-1,Tv Cidade Alagoinha Ao Vivo
https://video04.logicahost.com.br/tvcidade/tvcidade/playlist.m3u8

#EXTINF:-1,MyTime Movie Network - Brasil Ao Vivo
https://appletree-mytime-samsungbrazil.amagi.tv/playlist.m3u8

#EXTINF:-1,ABC BRASIL
https://stmv1.srvstm.com/victor7513/victor7513/playlist.m3u8

#EXTINF:-1,Tv Metropolitana Rio Ao Vivo
https://stmv1.srvstm.com/luis5346/luis5346/playlist.m3u8

#EXTINF:-1,Tv Web Sul Bahia Ao Vivo
https://a.cdni.live/radiomultimidia/radiomultimidia/playlist.m3u8

#EXTINF:-1,Top Mix Tv Filmes Ao Vivo
https://video03.logicahost.com.br/filmestopmixtv/filmestopmixtv/playlist.m3u8

#EXTINF:-1,Qtal Channel Ao Vivo
https://video03.logicahost.com.br/qtalchannel01/qtalchannel01/playlist.m3u8

#EXTINF:-1,Tv Adorando Jesus
https://stmv1.srvif.com/adorando/adorando/playlist.m3u8

#EXTINF:-1,Cindie Lite
https://stream.ads.ottera.tv/playlist.m3u8?network_id=1310

#EXTINF:-1,TV PANTANAL
https://59d39900ebfb8.streamlock.net:443/8040/8040/playlist.m3u8

#EXTINF:-1,TV Vila Real (Record MT) Ao Vivo
https://cdn.jmvstream.com/w/LVW-10841/LVW10841_mT77z9o2cP/playlist.m3u8

#EXTINF:-1,TV Vila Real
https://cdn.jmvstream.com/w/LVW-10842/LVW10842_513N26MDBL/chunklist_.m3u8




